#!/usr/bin/env bash
# Build supabase/setup/all-in-one.sql: every migration and seed in one file to
# paste into a new project's SQL Editor. Seeds run before the RLS migration so
# the inserts cannot be blocked by forced row-level security; RLS is switched
# on last, over the complete schema.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
M="$ROOT/supabase/migrations"
OUT="$ROOT/supabase/setup/all-in-one.sql"
mkdir -p "$(dirname "$OUT")"
{
  echo "-- ComeMorocco: complete database setup for a NEW Supabase project."
  echo "-- Supabase → SQL Editor → New query → paste everything → Run. Run it once."
  echo "-- Generated by scripts/build-supabase-setup.sh — do not edit by hand."
  for f in $(ls "$M"/*.sql | grep -v '_rls.sql$'); do echo; echo "-- ===== $(basename "$f")"; cat "$f"; done
  for f in "$ROOT"/supabase/seed/seed.sql "$ROOT"/supabase/seed/emergency_contacts.sql; do echo; echo "-- ===== seed: $(basename "$f")"; cat "$f"; done
  f=$(ls "$M"/*_rls.sql); echo; echo "-- ===== $(basename "$f") (last: switches on row-level security)"; cat "$f"
  echo; echo "select 'ComeMorocco setup complete' as status, (select count(*) from public.destinations) as destinations, (select count(*) from public.listings) as listings;"
} > "$OUT"
echo "wrote $OUT ($(wc -c < "$OUT") bytes)"
